### PR TITLE
Add purge of the sample dir in INBOX

### PR DESCRIPTION
**Pull request by ingkebil**
Haven't tested this tho.

The gist is that this way, the sample dir in the cust INBOX will be removed instead of just the fastq files. This of course also deletes all work the cust has done in that directory. The advantages are less clutter and no need to look up if we linked bam files or the like.

### CODE REVIEW

**Comment by ingkebil** [comment]
And related: removal of the fastq file links in MIP_ANALYSIS is now also included. No more dead links.

**Comment by ingkebil** [comment]
Also fixed _all_ links that lead from MIP_ANALYSIS to the actual fastq file.

**Comment by ingkebil** [comment]
Tested this now and it works flowlessly :dancer:

**Comment by vwirta** [comment]
working instread of watching the game?

vw

> On 1 jul 2016, at 22:52, Kenny Billiau <notifications@github.com> wrote:
> 
> Tested this now and it works flowlessly 💃
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/Clinical-Genomics/moneypenny/pull/31#issuecomment-230044852>, or mute the thread <https://github.com/notifications/unsubscribe/AChiGTG15eZT_QpGuIE4Nr5zfmyVGkufks5qRX4agaJpZM4JAg-g>.
> 

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna

**Comment by ingkebil** [comment]
of course! Pushed some other code into production just before I left so I could test part this easier. Amazed that it worked by coding diligently :hammer: 

Once this gets merged, I can remove fastq files for 110 cases :smile:

**Comment by ingkebil** [comment]
How in hell did Belgium lose? :o

**Pull request merged**
